[build]
  command = "pip install -r requirements.txt && python3 generate_static_site.py"
  publish = "dist"

[build.environment]
  PYTHON_VERSION = "3.8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
